### ISSUE TITLE
Redirect Issue in Kirby 2.2.2

### ISSUE THREAD

**Issue by jcwatson11** [JonasDoebertin/kirby-visual-markdown#65] opened 2015-11-24 17:48 UTC
We just upgraded to Kirby 2.2.2 and the markdown editor redirects back to the dashboard (or previous view) whenever you highlight some text and try to use any button in the editor (like bold or italicize). Clicking any button in the top button bar in the markdown editor redirects the browser back.

**Comment by 1n3JgKl9pQ6cUMrW** [comment] 2015-11-24 18:25
I don't have that issue with the developers-branche.

But may be the issue is caused because Kirby fires / hook **all** anchors, visibile in the panel.

![image](https://cloud.githubusercontent.com/assets/15701574/11376444/07cf38ae-92e1-11e5-8874-0906d467854d.png)

---

So maybe this Kirby-hook affects all the other anhors as well (I had that problem with my own plugin and had to rewrite all my anchors to buttons - because buttons are not affected).

**Comment by jcwatson11** [comment] 2015-11-24 20:06
Thanks for your response. I appreciate it. I'll look into what it would take to convert those to buttons (and see if it works) and maybe submit a pull request. I'll keep this thread updated with progress.

**Comment by jcwatson11** [comment] 2015-11-25 00:07
Check out Pull Request #66. Should fix the issue.

**Comment by JonasDoebertin** [comment] 2015-11-25 06:56
This has already been fixed on the `develop` branch and will ship with the next update (hopefully later today).

If you're interested: the easiest solution to fix this issue (which is caused by the panel, btw. and affects other plugins, too) is to simply give a `href` attribute to the links. Even if it's just `href="#"`. From my investigations, the issue will only happen when clicking links without it.

**Closed as completed by JonasDoebertin** 2015-11-25 06:56 UTC
Labels: bug, invalid
