### ISSUE TITLE
Can't save pages on an iPad

### ISSUE THREAD

**Issue by shoesforindustry** [JonasDoebertin/kirby-visual-markdown#35] opened 2015-06-01 15:41 UTC
I'm sorry I cannot provide more info on this, just me and my iPad and a poor network connection. When I try to save a page which contains the visual editor it just blanks and does not save. I can't see anything going on. If I try a page without the visual editor it saves as expected. 

IPad is latest AIr 128mb' latest iOS.

Any ideas?

**Comment by JonasDoebertin** [comment] 2015-06-02 09:41
Unfortunately no, I don't have a clue just now :(

Give me a day or two to have a closer look at this.

**Comment by shoesforindustry** [comment] 2015-06-13 06:27
Jonas have you had a chance to look at this yet?

**Comment by JonasDoebertin** [comment] 2015-06-17 14:12
I did have a look at it but I can't seem to be able to really track it down.

I can confirm that it happens only on pages with the Visual Markdown Editor on them and only on an iPad.

Tested with:
- Various desktop browsers: No issue
- iPad 1 / iOS 5.1.1: Issue
- Various android phones: No issue

Unfortunately, I don't have any newer iPads or an iPhone to test with at hand, right now.

**Comment by shoesforindustry** [comment] 2015-06-18 07:06
Is there anything I can help with to try and resolve this problem?

**Comment by JonasDoebertin** [comment] 2015-06-18 10:48
Send me a current iPad that doesn't crash when I try to debug the Panel? 😜

**Comment by shoesforindustry** [comment] 2015-06-18 11:12
Have you updated to the latest beta’s for Xcode/iOS? I’m not saying it will fix the crashing but it might?

Russ

**Comment by JonasDoebertin** [comment] 2015-06-18 11:14
I only have an iPad 1 stuck with iOS 5.1.1 at hand. Not much you can do there...

**Comment by erikfriberg** [comment] 2015-07-02 22:31
Hm I'm not 100% sure it's related but I have similar problems on iOS devices, except I actually get an error message:

Fatal error: Uncaught exception 'Exception' with message 'Invalid route' in /var/www/html/grafisk-journal/dist/panel/app/panel.php:222 Stack trace: #0 /var/www/html/grafisk-journal/dist/panel/index.php(47): Panel->launch() #1 {main} thrown in /var/www/html/grafisk-journal/dist/panel/app/panel.php on line 222

Again, unsure if the error is related to this plugin but it only shows up on pages where I use the markdown-input so it feels likely. I'll investigate some more tomorrow, will post if I find any clues.

**Comment by JonasDoebertin** [comment] 2015-09-18 14:31
Still not able to reproduce. Closing this for now.

**Closed as completed by JonasDoebertin** 2015-09-18 14:31 UTC
Labels: bug, help wanted, on hold
