### ISSUE TITLE
Reloading the panel destroys the editor

### ISSUE THREAD

**Issue by medienbaecker** [JonasDoebertin/kirby-visual-markdown#19] opened 2015-04-17 05:37 UTC
Reloading the panel when you're in the page editor destroys the editor. You'll then have to go back to the overview and click on the page again.

I've tested this in Chrome, Safari and Internet Explorer 9.

![untitled2](https://cloud.githubusercontent.com/assets/7975568/7196555/87d1d9be-e4d4-11e4-90cc-9660df5237ee.gif)

**Comment by JonasDoebertin** [comment] 2015-04-17 06:27
How do you reload the page? Via the standard browser shortcut?

I can't reproduce that behavior in Chrome and Safari on OSX. I can reload the page as much as I want, the editor always get's initialized correctly.

Have you checked the JavaScript console for any errors?

**Comment by medienbaecker** [comment] 2015-04-17 06:37
No matter how I reload, with CTRL+R or CMD+R depending on Mac/Windows or hitting the reload button.

I've recorded it again with the developer tools opened. Not a single error. I've even emptied my cache and tried another kirby installation.

![test](https://cloud.githubusercontent.com/assets/7975568/7197084/c179c55c-e4dc-11e4-8b6f-be3b35095007.gif)

**Comment by JonasDoebertin** [comment] 2015-04-17 06:47
I appears that the headline formatting isn't aligned (moved to the right) as expected within the editor on your second recording. Did you change any of the styles or any other file?

Are you using the _beta.3_ version of the editor? If yes, have you tried using the latest `develop` version?

I just double checked with the latest stable Kirby 2 and beta 2.1 releases and I can't reproduce the issue.

**Comment by medienbaecker** [comment] 2015-04-17 06:54
I didn't change any styles. And yes, I am indeed using the beta.3 on this installation. When recording the latest video I installed beta.1 or beta.2 I guess. That's why the grey "#" is not on the left

When I was checking another installation I also installed the stable visual-markdown release:

![untitled3](https://cloud.githubusercontent.com/assets/7975568/7197272/4627aa10-e4df-11e4-9163-aa0dabd7d5eb.gif)

But I guess it's impossible to fix if you can't reproduce the issue. I really don't understand why it's only my computers (two desktops and one notebook).

Have you tried emptying **your** cache? Maybe something's cached for you that I don't have?

**Comment by JonasDoebertin** [comment] 2015-04-17 09:39
I did try that. It doesn't change anything.

I'll do some further investigations and tests on other machines later today. Maybe I can find out more about the root of the issue.

**Comment by medienbaecker** [comment] 2015-04-17 09:53
Alright. Thanks for your patience on this very weird issue.
To help your investigations I've set up a new server with Kirby 2.1 Starterpack on which I can experience the issue:

http://p249378.mittwaldserver.info/panel
user: issue-19
password: issue#19

**Comment by JonasDoebertin** [comment] 2015-04-17 12:56
Thanks to your demo setup, I was able to track down the root cause of the issue. You may want to have a look at this issue I created: getkirby/panel#435.

Hopefully, Bastian will be able to have a look at it, soon.

**Comment by JonasDoebertin** [comment] 2015-04-21 06:44
Seems like Bastian is busy with other things right now.

I'll leave this issue open for future reference and come back to it once we hear about getkirby/panel#435.

**Comment by JonasDoebertin** [comment] 2015-05-29 07:42
Quick heads up: I haven't heard back yet about the issue I opened at the panel repo :(

**Comment by JonasDoebertin** [comment] 2015-09-18 14:31
I guess there's nothing we can do here as it's an issue in the panel. Closing this for now.

**Closed as completed by JonasDoebertin** 2015-09-18 14:31 UTC
Labels: bug, on hold
