### ISSUE TITLE
Dupolicated VM Editor after click on URL-Appendix on Kirby 2.2.1

### ISSUE THREAD

**Issue by isaactopo** [JonasDoebertin/kirby-visual-markdown#61] opened 2015-11-18 10:00 UTC
Hi, I updated to Kirby 2.2.1 and I'm experimenting a “VM top-bar” duplication every time I click on the new link on the bottom of Title to change URL-Appendix:

![captura de pantalla 2015-11-18 a la s 10 55 22 2](https://cloud.githubusercontent.com/assets/4568596/11238050/7138ea90-8de3-11e5-9186-a3d8f38e37c6.png)

I tested this on Firefox and Chrome.

**Comment by 1n3JgKl9pQ6cUMrW** [comment] 2015-11-18 21:15
![image](https://cloud.githubusercontent.com/assets/15701574/11254527/86bc76f8-8e41-11e5-8d1a-b8aa3669ab18.png)

This is also happening when using the default structure field, so it has to do something with the modal (which is triggered by both the url-slug and the structured-field).

Things to reproduce;
1. Create  a structure field.
2. Create a (default) markdown field.
3. Add a new entry to the structure field.
4. Click **cancel** (clicking **okay** works fine).
5. You now have a duplicate markdown field (both buttons, and content).
6. You can also try to **delete** a structure field and click **cancel** - (the button-bar and the text-content will show up as a new duplicate inside the markdown-area).

**Comment by 1n3JgKl9pQ6cUMrW** [comment] 2015-11-18 21:28
**\- update -**

I also tried the developers version;

https://github.com/JonasDoebertin/kirby-visual-markdown/tree/develop

But this branche doesn't work at all with Kirby 2.2.1

It does not show any buttons and the height of the text-area is not adjusted.

Also it throws a Javascript-error in the console;

`Uncaught ReferenceError: CodeMirror is not defined`

So maybe this error causes the plug-in to break it's own functions.

**Comment by JonasDoebertin** [comment] 2015-11-19 07:47
Hi guys,

I'm aware that Visual Markdown Editor isn't working with the panel changes in Kirby 2.2 right now. Unfortunately, it will take me another few days to get to tackle the issues you noticed.

_Note: The `develop` branch shouldn't be used, especially not in production, as it may contain unstable or partly broken states at any times._

**Comment by shoesforindustry** [comment] 2015-11-24 08:13
Is there any news on this? I appreciate you are very busy, but I guess lots of people have sites they want to upgrade to Kirby 2.2.2, but cannot because they use this plugin?

**Comment by JonasDoebertin** [comment] 2015-11-24 09:27
Could you give the current version on the `develop` branch a spin? It should fix all Kirby 2.2 related issues and introduce some more fixes. [Here's what's new](https://github.com/JonasDoebertin/kirby-visual-markdown/blob/develop/CHANGELOG.md).

**Comment by shoesforindustry** [comment] 2015-11-24 11:00
HI Jonas, I can now see the text and the toolbar, but there are a couple of issues (Firefox Mac)
1. The help menu disappears behind the text.
<img width="164" alt="screen shot 2015-11-24 at 10 35 56" src="https://cloud.githubusercontent.com/assets/2102743/11364764/4f5f96ec-929a-11e5-978a-1fd3b10252a3.png">
2. The header toolbar does not seem sticky? e.g. it scrolls off the top of the screen.
Let me know if you want any more information.

**Comment by JonasDoebertin** [comment] 2015-11-24 11:03
Thanks for your insights.
1. I'm able to reproduce that. Will be fixed.
2. The toolbar was changed to be sticky only if the field is focussed. Once you focus the field the toolbar should appear. Can you confirm this? Do you see any JS errors in the console?

**Comment by shoesforindustry** [comment] 2015-11-24 11:07
1. Cool
2. Sorry I misunderstood, I can confirm that when focussed it is sticky, nice idea!
   No other problems so far.

**Comment by 1n3JgKl9pQ6cUMrW** [comment] 2015-11-24 16:13
Just tried the `developers branche` in Kirby 2.2.2 - the error is still there.

![image](https://cloud.githubusercontent.com/assets/15701574/11372586/8bd3e0cc-92ce-11e5-8e3f-ccc5f0d98464.png)

**Reproduce**
- Go to a page with the Markdown Field
- Open a modal (e.g. when changing the URL slug)
- Press _cancel_ on the modal
- The content of the Markdown Field is magically doubled

**Comment by 1n3JgKl9pQ6cUMrW** [comment] 2015-11-24 17:37
Okay, maybe a quick fix.

I downloaded the `developers-branche` and changed this file;

_site/fields/markdown/assets/js/visualmarkdownfield.js_

I changed **line #290** with the function below. It's quick and dirty - but it works (as a work around).

It simply checks if the Markdown Field already has a toolbar... if not; it fires the field, if it has a toolbar, it skips the function for this field and goes on to the next field.

**I debugged and coded it in 5 minutes, so it may be not an official solution - but at least I can update to Kirby 2.2.2**

``` JS
    $.fn.markdownfield = function()
      {
    if(!$(this).parent().find('ul.visualmarkdown-toolbar').length)
      {
    return new VisualMarkdownField($,this);
      }
      };
```

**Comment by JonasDoebertin** [comment] 2015-11-25 07:30
From what I found out this happens when a modal is closed without the panel page being reloaded (eg. you cancel a modal window). It seems as if the panel reruns the field initialization code when this happens were it clearly shouldn't.

**Comment by JonasDoebertin** [comment] 2015-11-25 07:47
I implemented a hotfix with 0def1aefffbe36401b99fb9505ca9d5bad0ca67b.

@1n3JgKl9pQ6cUMrW @isaactopo Could you checkout if this solves your issue?

**Comment by 1n3JgKl9pQ6cUMrW** [comment] 2015-11-25 11:33
@JonasDoebertin

I tried the developers-branche and can confirm "canceling" a modal is not affecting the content of the Markdown Field - so the fix works.

It looks like my own fix (see message above) but yours' more elegant :)

It looks like Kirby is (re-)loading / (re-firing) the assets when you cancel a model. It also effects other plugins, so I'm not sure this is done by design or a bug...

I initialize my field the way Bastian recommended;

https://forum.getkirby.com/t/kirby-2-2-how-to-check-if-panel-is-loaded/2530

...but canceling the modal does fire them twice - so I have to check them the same way you did.

Thanks for pointing me in the right direction!

**Comment by JonasDoebertin** [comment] 2015-11-26 08:08
Seems like this issue is fixed now so I'm closing it.

Please let me know if it ever happens again!

**Closed as completed by JonasDoebertin** 2015-11-26 08:08 UTC
Labels: bug

**Comment by 1n3JgKl9pQ6cUMrW** [comment] 2015-11-26 14:23
Great, thanks for your hard work!

**Comment by isaactopo** [comment] 2015-12-01 15:58
Working perfect, thanks @JonasDoebertin !
